import type {
  Order,
  Product,
  Combo,
  InventoryItem,
  Employee,
  Attendance,
  Income,
} from '@/types'

// Products
export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Salmón Roll',
    description: '8 piezas de roll con salmón fresco, palta y queso crema',
    priceMostrador: 4500,
    pricePedidosYa: 5400,
    category: 'Rolls',
    available: true,
  },
  {
    id: 'p2',
    name: 'Philadelphia Roll',
    description: '8 piezas con salmón ahumado, queso philadelphia y pepino',
    priceMostrador: 4200,
    pricePedidosYa: 5000,
    category: 'Rolls',
    available: true,
  },
  {
    id: 'p3',
    name: 'Tempura Roll',
    description: '8 piezas empanizadas con langostino y vegetales',
    priceMostrador: 4800,
    pricePedidosYa: 5760,
    category: 'Rolls',
    available: true,
  },
  {
    id: 'p4',
    name: 'California Roll',
    description: '8 piezas con kanikama, palta y pepino',
    priceMostrador: 3500,
    pricePedidosYa: 4200,
    category: 'Rolls',
    available: true,
  },
  {
    id: 'p5',
    name: 'Nigiri Salmón x2',
    description: '2 piezas de nigiri con salmón fresco',
    priceMostrador: 1800,
    pricePedidosYa: 2160,
    category: 'Nigiris',
    available: true,
  },
  {
    id: 'p6',
    name: 'Sashimi Salmón x5',
    description: '5 láminas de salmón fresco',
    priceMostrador: 3200,
    pricePedidosYa: 3840,
    category: 'Sashimis',
    available: true,
  },
  {
    id: 'p7',
    name: 'Gyozas x6',
    description: 'Empanaditas japonesas de cerdo y vegetales',
    priceMostrador: 2800,
    pricePedidosYa: 3360,
    category: 'Entradas',
    available: true,
  },
  {
    id: 'p8',
    name: 'Edamame',
    description: 'Porotos de soja con sal marina',
    priceMostrador: 1500,
    pricePedidosYa: 1800,
    category: 'Entradas',
    available: false,
  },
]

// Combos
export const mockCombos: Combo[] = [
  {
    id: 'c1',
    name: 'Combo Pareja',
    description: '20 piezas variadas + 2 bebidas',
    products: [
      { productId: 'p1', quantity: 1 },
      { productId: 'p2', quantity: 1 },
      { productId: 'p4', quantity: 1 },
    ],
    priceMostrador: 8900,
    pricePedidosYa: 10680,
    available: true,
  },
  {
    id: 'c2',
    name: 'Combo Familiar',
    description: '40 piezas variadas + 4 bebidas',
    products: [
      { productId: 'p1', quantity: 2 },
      { productId: 'p2', quantity: 2 },
      { productId: 'p3', quantity: 1 },
    ],
    priceMostrador: 15900,
    pricePedidosYa: 19080,
    available: true,
  },
  {
    id: 'c3',
    name: 'Combo Individual',
    description: '12 piezas + bebida',
    products: [
      { productId: 'p1', quantity: 1 },
      { productId: 'p5', quantity: 2 },
    ],
    priceMostrador: 5500,
    pricePedidosYa: 6600,
    available: true,
  },
]

// Orders
export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    items: [
      { id: 'i1', name: 'Combo Pareja', quantity: 1, price: 8900 },
      { id: 'i2', name: 'Gyozas x6', quantity: 1, price: 2800 },
    ],
    status: 'nuevo',
    source: 'pedidosya',
    customerName: 'María García',
    customerPhone: '341-5551234',
    customerAddress: 'Av. Pellegrini 1234, Rosario',
    totalMostrador: 11700,
    totalPedidosYa: 14040,
    paymentMethod: 'credito',
    createdAt: new Date(Date.now() - 2 * 60 * 1000),
  },
  {
    id: 'ORD-002',
    items: [
      { id: 'i3', name: 'Salmón Roll', quantity: 2, price: 9000 },
      { id: 'i4', name: 'Philadelphia Roll', quantity: 1, price: 4200 },
    ],
    status: 'preparando',
    source: 'mostrador',
    customerName: 'Juan Pérez',
    customerPhone: '341-5559876',
    totalMostrador: 13200,
    paymentMethod: 'efectivo',
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
  },
  {
    id: 'ORD-003',
    items: [
      { id: 'i5', name: 'Combo Familiar', quantity: 1, price: 15900 },
    ],
    status: 'preparando',
    source: 'pedidosya',
    customerName: 'Carlos Rodríguez',
    customerPhone: '341-5554567',
    customerAddress: 'Córdoba 2500, Rosario',
    totalMostrador: 15900,
    totalPedidosYa: 19080,
    paymentMethod: 'debito',
    createdAt: new Date(Date.now() - 25 * 60 * 1000),
  },
  {
    id: 'ORD-004',
    items: [
      { id: 'i6', name: 'California Roll', quantity: 3, price: 10500 },
      { id: 'i7', name: 'Edamame', quantity: 2, price: 3000 },
    ],
    status: 'listo',
    source: 'mostrador',
    customerName: 'Ana Martínez',
    totalMostrador: 13500,
    paymentMethod: 'transferencia',
    createdAt: new Date(Date.now() - 35 * 60 * 1000),
  },
  {
    id: 'ORD-005',
    items: [
      { id: 'i8', name: 'Tempura Roll', quantity: 2, price: 9600 },
    ],
    status: 'nuevo',
    source: 'pedidosya',
    customerName: 'Lucas Fernández',
    customerPhone: '341-5552345',
    customerAddress: 'San Martín 800, Rosario',
    totalMostrador: 9600,
    totalPedidosYa: 11520,
    paymentMethod: 'credito',
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
  },
]

// Inventory
export const mockInventory: InventoryItem[] = [
  {
    id: 'inv1',
    name: 'Salmón Fresco',
    quantity: 3.5,
    unit: 'kg',
    minStock: 5,
    category: 'Pescados',
    lastUpdated: new Date(),
  },
  {
    id: 'inv2',
    name: 'Arroz para Sushi',
    quantity: 25,
    unit: 'kg',
    minStock: 10,
    category: 'Básicos',
    lastUpdated: new Date(),
  },
  {
    id: 'inv3',
    name: 'Nori (Alga)',
    quantity: 50,
    unit: 'hojas',
    minStock: 100,
    category: 'Básicos',
    lastUpdated: new Date(),
  },
  {
    id: 'inv4',
    name: 'Queso Crema',
    quantity: 8,
    unit: 'kg',
    minStock: 5,
    category: 'Lácteos',
    lastUpdated: new Date(),
  },
  {
    id: 'inv5',
    name: 'Palta',
    quantity: 2,
    unit: 'kg',
    minStock: 4,
    category: 'Vegetales',
    lastUpdated: new Date(),
  },
  {
    id: 'inv6',
    name: 'Langostinos',
    quantity: 4,
    unit: 'kg',
    minStock: 3,
    category: 'Mariscos',
    lastUpdated: new Date(),
  },
  {
    id: 'inv7',
    name: 'Salsa de Soja',
    quantity: 12,
    unit: 'litros',
    minStock: 5,
    category: 'Condimentos',
    lastUpdated: new Date(),
  },
  {
    id: 'inv8',
    name: 'Wasabi',
    quantity: 0.3,
    unit: 'kg',
    minStock: 0.5,
    category: 'Condimentos',
    lastUpdated: new Date(),
  },
]

// Employees
export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    name: 'Roberto Sushi',
    email: 'roberto@rosariosushi.com',
    phone: '341-5551111',
    role: 'admin',
    active: true,
    createdAt: new Date('2023-01-15'),
  },
  {
    id: 'emp2',
    name: 'Laura Cocina',
    email: 'laura@rosariosushi.com',
    phone: '341-5552222',
    role: 'empleado',
    active: true,
    createdAt: new Date('2023-03-20'),
  },
  {
    id: 'emp3',
    name: 'Miguel Caja',
    email: 'miguel@rosariosushi.com',
    phone: '341-5553333',
    role: 'empleado',
    active: true,
    createdAt: new Date('2023-06-10'),
  },
  {
    id: 'emp4',
    name: 'Sofia Delivery',
    email: 'sofia@rosariosushi.com',
    phone: '341-5554444',
    role: 'empleado',
    active: false,
    createdAt: new Date('2024-01-05'),
  },
]

// Attendance
export const mockAttendance: Attendance[] = [
  {
    id: 'att1',
    employeeId: 'emp2',
    employeeName: 'Laura Cocina',
    date: new Date(),
    checkIn: new Date(new Date().setHours(10, 0, 0)),
    checkOut: new Date(new Date().setHours(18, 30, 0)),
    hoursWorked: 8.5,
  },
  {
    id: 'att2',
    employeeId: 'emp3',
    employeeName: 'Miguel Caja',
    date: new Date(),
    checkIn: new Date(new Date().setHours(11, 0, 0)),
  },
  {
    id: 'att3',
    employeeId: 'emp2',
    employeeName: 'Laura Cocina',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    checkIn: new Date(new Date(Date.now() - 24 * 60 * 60 * 1000).setHours(10, 0, 0)),
    checkOut: new Date(new Date(Date.now() - 24 * 60 * 60 * 1000).setHours(19, 0, 0)),
    hoursWorked: 9,
  },
]

// Income/Finance
export const mockIncome: Income[] = [
  {
    id: 'inc1',
    orderId: 'ORD-001',
    amount: 14040,
    type: 'blanco',
    paymentMethod: 'credito',
    date: new Date(),
    description: 'Pedido PedidosYa - Combo Pareja + Gyozas',
  },
  {
    id: 'inc2',
    orderId: 'ORD-002',
    amount: 13200,
    type: 'negro',
    paymentMethod: 'efectivo',
    date: new Date(),
    description: 'Pedido Mostrador - Rolls variados',
  },
  {
    id: 'inc3',
    orderId: 'ORD-003',
    amount: 19080,
    type: 'blanco',
    paymentMethod: 'debito',
    date: new Date(),
    description: 'Pedido PedidosYa - Combo Familiar',
  },
  {
    id: 'inc4',
    orderId: 'ORD-004',
    amount: 13500,
    type: 'blanco',
    paymentMethod: 'transferencia',
    date: new Date(),
    description: 'Pedido Mostrador - California + Edamame',
  },
  {
    id: 'inc5',
    orderId: 'ORD-100',
    amount: 8500,
    type: 'negro',
    paymentMethod: 'efectivo',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    description: 'Pedido Mostrador - Varios',
  },
  {
    id: 'inc6',
    orderId: 'ORD-101',
    amount: 22000,
    type: 'blanco',
    paymentMethod: 'credito',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    description: 'Pedido PedidosYa - Pedido grande',
  },
]

// Finance statistics by period
export const mockFinanceStats = {
  today: {
    totalBlanco: 46620,
    totalNegro: 13200,
    totalOrders: 4,
    averageTicket: 14955,
    byPaymentMethod: {
      efectivo: 13200,
      debito: 19080,
      credito: 14040,
      transferencia: 13500,
    },
  },
  week: {
    totalBlanco: 285000,
    totalNegro: 98000,
    totalOrders: 45,
    averageTicket: 8511,
    byPaymentMethod: {
      efectivo: 98000,
      debito: 95000,
      credito: 120000,
      transferencia: 70000,
    },
  },
  month: {
    totalBlanco: 1250000,
    totalNegro: 420000,
    totalOrders: 198,
    averageTicket: 8434,
    byPaymentMethod: {
      efectivo: 420000,
      debito: 380000,
      credito: 550000,
      transferencia: 320000,
    },
  },
}

// Chart data for finances
export const mockChartData = {
  weekly: [
    { day: 'Lun', blanco: 45000, negro: 12000 },
    { day: 'Mar', blanco: 38000, negro: 15000 },
    { day: 'Mié', blanco: 52000, negro: 18000 },
    { day: 'Jue', blanco: 48000, negro: 14000 },
    { day: 'Vie', blanco: 65000, negro: 22000 },
    { day: 'Sáb', blanco: 78000, negro: 28000 },
    { day: 'Dom', blanco: 42000, negro: 9000 },
  ],
  monthly: [
    { week: 'Sem 1', blanco: 280000, negro: 95000 },
    { week: 'Sem 2', blanco: 320000, negro: 110000 },
    { week: 'Sem 3', blanco: 295000, negro: 102000 },
    { week: 'Sem 4', blanco: 355000, negro: 113000 },
  ],
}
